/**
 * SatFinder Pro - Satellite Database
 * Contains 200+ geostationary satellites with their orbital positions
 */

const SATELLITES = [
    // Popular TV Satellites
    { name: "Hotbird 13B/13C/13E", position: 13.0, region: "Europe, Middle East, North Africa" },
    { name: "Astra 1KR/1L/1M/1N", position: 19.2, region: "Europe" },
    { name: "Astra 2E/2F/2G", position: 28.2, region: "UK, Ireland" },
    { name: "Astra 3B", position: 23.5, region: "Europe" },
    { name: "Astra 4A", position: 4.8, region: "Northern Europe" },
    { name: "Eutelsat 7A/7B", position: 7.0, region: "Europe, Turkey, Middle East" },
    { name: "Eutelsat 8 West B", position: -8.0, region: "North Africa, Middle East" },
    { name: "Eutelsat 9B", position: 9.0, region: "Europe" },
    { name: "Eutelsat 10A", position: 10.0, region: "Europe, Middle East, Africa" },
    { name: "Eutelsat 16A", position: 16.0, region: "Balkans, Turkey" },
    { name: "Eutelsat 21B", position: 21.5, region: "Europe, Middle East" },
    { name: "Eutelsat 25B", position: 25.5, region: "Europe, Middle East" },
    { name: "Eutelsat 33E", position: 33.0, region: "Europe, Africa" },
    { name: "Eutelsat 36B", position: 36.0, region: "Russia, Africa" },
    { name: "Eurobird 1", position: 28.5, region: "Europe" },
    { name: "Nilesat 201/202", position: 7.0, region: "Middle East, North Africa" },
    { name: "Arabsat 5A", position: 30.5, region: "Middle East, Africa" },
    { name: "Arabsat 5C", position: 20.0, region: "Middle East, Africa" },
    { name: "Arabsat 6A", position: 30.5, region: "Middle East, Africa" },
    { name: "Badr 4/5/6/7", position: 26.0, region: "Middle East, Africa" },
    { name: "Türksat 3A/4A", position: 42.0, region: "Turkey, Europe, Central Asia" },
    { name: "Türksat 4B", position: 50.0, region: "Turkey, Middle East, Africa" },
    { name: "Türksat 5A", position: 31.0, region: "Turkey" },
    { name: "Thor 5/6/7", position: 0.8, region: "Europe" },
    { name: "Intelsat 10-02", position: 0.8, region: "Europe, Africa" },
    { name: "Intelsat 901", position: 27.5, region: "Atlantic" },
    { name: "Intelsat 902", position: 62.0, region: "Europe, Africa" },
    { name: "Intelsat 903", position: 34.5, region: "Atlantic" },
    { name: "Intelsat 904", position: 60.0, region: "Europe, Middle East" },
    { name: "Intelsat 905", position: 24.5, region: "Atlantic" },
    { name: "Intelsat 906", position: 64.2, region: "Europe, Africa" },
    { name: "Intelsat 907", position: 27.5, region: "Atlantic" },
    { name: "Intelsat 10", position: 68.5, region: "Europe, Central Asia" },
    { name: "Intelsat 12", position: 45.0, region: "Europe, Middle East, Africa" },
    { name: "Intelsat 17", position: 66.0, region: "Europe, Middle East" },
    { name: "Intelsat 19", position: 166.0, region: "Pacific" },
    { name: "Intelsat 20", position: 68.5, region: "Europe, Africa, Middle East" },
    { name: "SES-4", position: -22.0, region: "Americas, Europe, Africa" },
    { name: "SES-5", position: 5.0, region: "Europe, Africa" },
    { name: "SES-6", position: -40.5, region: "Americas, Atlantic" },
    
    // Americas
    { name: "DirecTV 10/12/15", position: -103.0, region: "North America" },
    { name: "DirecTV 11/14", position: -99.0, region: "North America" },
    { name: "Echostar 10/11", position: -110.0, region: "North America" },
    { name: "Echostar 14", position: -119.0, region: "North America" },
    { name: "Galaxy 3C", position: -95.0, region: "North America" },
    { name: "Galaxy 11", position: -91.0, region: "Americas" },
    { name: "Galaxy 12", position: -93.0, region: "Americas" },
    { name: "Galaxy 13/Horizons 1", position: -127.0, region: "North America, Pacific" },
    { name: "Galaxy 14", position: -125.0, region: "North America" },
    { name: "Galaxy 15", position: -133.0, region: "North America" },
    { name: "Galaxy 16", position: -99.0, region: "North America" },
    { name: "Galaxy 17", position: -91.0, region: "Americas" },
    { name: "Galaxy 18", position: -123.0, region: "North America" },
    { name: "Galaxy 19", position: -97.0, region: "North America" },
    { name: "Galaxy 23", position: -121.0, region: "North America" },
    { name: "Galaxy 28", position: -89.0, region: "North America" },
    { name: "AMC 1", position: -103.0, region: "North America" },
    { name: "AMC 3", position: -87.0, region: "North America" },
    { name: "AMC 4", position: -101.0, region: "North America" },
    { name: "AMC 5", position: -79.0, region: "Americas" },
    { name: "AMC 6", position: -72.0, region: "Americas" },
    { name: "AMC 7", position: -137.0, region: "North America" },
    { name: "AMC 8", position: -139.0, region: "North America" },
    { name: "AMC 9", position: -83.0, region: "North America" },
    { name: "AMC 10/11", position: -135.0, region: "North America" },
    { name: "AMC 15/18", position: -105.0, region: "North America" },
    { name: "AMC 21", position: -125.0, region: "North America" },
    { name: "Nimiq 1", position: -91.0, region: "Canada" },
    { name: "Nimiq 2", position: -82.0, region: "Canada" },
    { name: "Nimiq 4", position: -82.0, region: "Canada" },
    { name: "Nimiq 5", position: -72.7, region: "Canada" },
    { name: "Nimiq 6", position: -91.0, region: "Canada" },
    { name: "Anik F1", position: -107.3, region: "Canada" },
    { name: "Anik F1R", position: -107.3, region: "Canada" },
    { name: "Anik F2", position: -111.1, region: "Canada" },
    { name: "Anik F3", position: -118.7, region: "Canada" },
    { name: "Anik G1", position: -107.3, region: "Canada" },
    { name: "Hispasat 1C", position: -30.0, region: "Americas, Europe" },
    { name: "Hispasat 1D", position: -30.0, region: "Americas, Europe" },
    { name: "Hispasat 1E", position: -30.0, region: "Americas, Europe" },
    { name: "Amazonas 2", position: -61.0, region: "Americas" },
    { name: "Amazonas 3", position: -61.0, region: "Americas" },
    { name: "NSS-806", position: -47.5, region: "Americas, Atlantic" },
    { name: "Intelsat Americas 5", position: -97.0, region: "Americas" },
    { name: "Intelsat Americas 7", position: -129.0, region: "Americas" },
    { name: "Intelsat Americas 8", position: -89.0, region: "Americas" },
    { name: "Star One C1", position: -65.0, region: "South America" },
    { name: "Star One C2", position: -70.0, region: "South America" },
    { name: "Star One C3", position: -75.0, region: "South America" },
    { name: "Star One C4", position: -70.0, region: "South America" },
    { name: "Star One D1", position: -84.0, region: "South America" },
    
    // Asia & Pacific
    { name: "AsiaSat 3S", position: 105.5, region: "Asia" },
    { name: "AsiaSat 4", position: 122.0, region: "Asia, Australia" },
    { name: "AsiaSat 5", position: 100.5, region: "Asia" },
    { name: "AsiaSat 6", position: 120.0, region: "Asia" },
    { name: "AsiaSat 7", position: 105.5, region: "Asia" },
    { name: "AsiaSat 8", position: 105.5, region: "Asia" },
    { name: "AsiaSat 9", position: 122.0, region: "Asia, Australia" },
    { name: "ChinaSat 6A", position: 125.0, region: "China" },
    { name: "ChinaSat 6B", position: 115.5, region: "China" },
    { name: "ChinaSat 9", position: 92.2, region: "China" },
    { name: "ChinaSat 9A", position: 92.2, region: "China" },
    { name: "ChinaSat 10", position: 110.5, region: "China" },
    { name: "ChinaSat 11", position: 98.0, region: "China" },
    { name: "ChinaSat 12", position: 87.5, region: "China, South Asia" },
    { name: "ChinaSat 16", position: 110.5, region: "China" },
    { name: "Apstar 5C", position: 138.0, region: "Asia Pacific" },
    { name: "Apstar 6", position: 134.0, region: "Asia Pacific" },
    { name: "Apstar 6C", position: 134.0, region: "Asia Pacific" },
    { name: "Apstar 7", position: 76.5, region: "Asia, Middle East" },
    { name: "Apstar 9", position: 142.0, region: "Asia Pacific" },
    { name: "Thaicom 4", position: 119.5, region: "Asia, Australia" },
    { name: "Thaicom 5", position: 78.5, region: "Asia" },
    { name: "Thaicom 6", position: 78.5, region: "Asia" },
    { name: "Thaicom 7", position: 120.0, region: "Asia" },
    { name: "Thaicom 8", position: 78.5, region: "Asia, Africa" },
    { name: "JCSAT-3A", position: 128.0, region: "Japan, Asia" },
    { name: "JCSAT-4B", position: 124.0, region: "Japan, Asia" },
    { name: "JCSAT-5A", position: 132.0, region: "Japan" },
    { name: "JCSAT-110R", position: 110.0, region: "Japan" },
    { name: "N-Star c", position: 136.0, region: "Japan" },
    { name: "Superbird B2", position: 162.0, region: "Japan, Pacific" },
    { name: "Superbird C2", position: 144.0, region: "Japan, Asia" },
    { name: "Koreasat 5", position: 113.0, region: "Korea" },
    { name: "Koreasat 6", position: 116.0, region: "Korea" },
    { name: "Koreasat 7", position: 116.0, region: "Korea, Indonesia" },
    { name: "Measat 3", position: 91.5, region: "Asia" },
    { name: "Measat 3a", position: 91.5, region: "Asia" },
    { name: "Measat 3b", position: 91.5, region: "Asia, Africa" },
    { name: "NSS-6", position: 95.0, region: "Asia, Middle East" },
    { name: "Palapa D", position: 113.0, region: "Indonesia, Southeast Asia" },
    { name: "Telkom 1", position: 108.0, region: "Indonesia" },
    { name: "Telkom 2", position: 118.0, region: "Indonesia" },
    { name: "Telkom 3S", position: 118.0, region: "Indonesia" },
    { name: "Vinasat 1", position: 132.0, region: "Vietnam, Southeast Asia" },
    { name: "Vinasat 2", position: 131.8, region: "Vietnam, Southeast Asia" },
    { name: "Optus C1", position: 156.0, region: "Australia" },
    { name: "Optus D1", position: 160.0, region: "Australia, New Zealand" },
    { name: "Optus D2", position: 152.0, region: "Australia" },
    { name: "Optus D3", position: 156.0, region: "Australia, New Zealand" },
    { name: "Intelsat 18", position: 180.0, region: "Pacific" },
    { name: "Express AM3", position: 140.0, region: "Russia, Asia" },
    { name: "Express AM5", position: 140.0, region: "Russia, Asia" },
    { name: "Express AM6", position: 53.0, region: "Russia, Europe" },
    { name: "Express AM7", position: 40.0, region: "Europe, Middle East" },
    { name: "Express AM8", position: 14.0, region: "Europe, Africa" },
    { name: "Yamal 202", position: 49.0, region: "Russia, Europe, Middle East" },
    { name: "Yamal 300K", position: 183.0, region: "Russia, Americas" },
    { name: "Yamal 401", position: 90.0, region: "Russia, South Asia" },
    { name: "Yamal 402", position: 55.0, region: "Russia, Middle East" },
    { name: "Yamal 601", position: 49.0, region: "Russia, Europe" },
    
    // India
    { name: "GSAT-6", position: 83.0, region: "India" },
    { name: "GSAT-7", position: 74.0, region: "India" },
    { name: "GSAT-8", position: 55.0, region: "India" },
    { name: "GSAT-9", position: 48.0, region: "South Asia" },
    { name: "GSAT-10", position: 83.0, region: "India" },
    { name: "GSAT-11", position: 74.0, region: "India" },
    { name: "GSAT-12", position: 83.0, region: "India" },
    { name: "GSAT-14", position: 74.0, region: "India" },
    { name: "GSAT-15", position: 93.5, region: "India" },
    { name: "GSAT-16", position: 55.0, region: "India" },
    { name: "GSAT-17", position: 93.5, region: "India" },
    { name: "GSAT-18", position: 74.0, region: "India" },
    { name: "GSAT-19", position: 48.0, region: "India" },
    { name: "GSAT-30", position: 83.0, region: "India" },
    { name: "GSAT-31", position: 48.0, region: "India" },
    { name: "INSAT-3A", position: 93.5, region: "India" },
    { name: "INSAT-3C", position: 74.0, region: "India" },
    { name: "INSAT-4A", position: 83.0, region: "India" },
    { name: "INSAT-4B", position: 93.5, region: "India" },
    { name: "INSAT-4CR", position: 74.0, region: "India" },
    { name: "SES-8", position: 95.0, region: "Asia Pacific" },
    { name: "SES-7", position: 108.2, region: "Asia Pacific" },
    { name: "SES-9", position: 108.2, region: "Asia Pacific" },
    
    // Africa
    { name: "Eutelsat 5 West A", position: -5.0, region: "Europe, North Africa" },
    { name: "Eutelsat 5 West B", position: -5.0, region: "Europe, North Africa, Middle East" },
    { name: "Eutelsat 7 West A", position: -7.3, region: "Middle East, North Africa" },
    { name: "Eutelsat KONNECT", position: 7.0, region: "Europe, Africa" },
    { name: "Rascom-QAF 1R", position: 2.9, region: "Africa" },
    { name: "Amos 5", position: 17.0, region: "Africa" },
    { name: "Amos 6", position: 4.0, region: "Middle East, Europe" },
    { name: "Amos 7", position: 4.0, region: "Middle East, Europe" },
    { name: "Amos 17", position: 17.0, region: "Africa" },
    { name: "ABS-2", position: 75.0, region: "Middle East, Africa, Asia" },
    { name: "ABS-2A", position: 75.0, region: "Middle East, Africa, South Asia" },
    { name: "ABS-3A", position: 3.0, region: "Americas, Europe, Africa" },
    { name: "ABS-4/Mobisat 1", position: -61.0, region: "Americas" },
    { name: "ABS-6", position: 159.0, region: "Asia Pacific" },
    { name: "Nigcomsat 1R", position: 42.5, region: "Africa" },
    { name: "Spacecom AMOS-3", position: 4.0, region: "Europe, Middle East" },
    { name: "Spacecom AMOS-4", position: 65.0, region: "Middle East, Asia" },
    
    // Additional Global Satellites
    { name: "Inmarsat 5-F1", position: 62.6, region: "Europe, Middle East, Africa" },
    { name: "Inmarsat 5-F2", position: -55.0, region: "Americas, Atlantic" },
    { name: "Inmarsat 5-F3", position: 179.6, region: "Pacific" },
    { name: "Inmarsat 5-F4", position: -97.6, region: "Americas" },
    { name: "NBN-Co 1A", position: 140.0, region: "Australia" },
    { name: "NBN-Co 1B", position: 149.0, region: "Australia" },
    { name: "ViaSat-1", position: -115.1, region: "North America" },
    { name: "ViaSat-2", position: -69.9, region: "Americas" },
    { name: "EchoStar XVII", position: -107.1, region: "North America" },
    { name: "EchoStar XIX", position: -97.1, region: "North America" },
    { name: "Hughes Jupiter 1", position: -99.0, region: "North America" },
    { name: "Hughes Jupiter 2", position: -110.0, region: "North America" },
    { name: "Es'hail 2", position: 25.9, region: "Middle East, Africa" },
    { name: "Es'hailSat 1", position: 25.5, region: "Middle East" },
    { name: "Paksat 1R", position: 38.0, region: "Pakistan, South Asia" },
    { name: "Paksat MM1", position: 38.2, region: "Pakistan, Central Asia" },
    { name: "BRIsat", position: 150.5, region: "Indonesia" },
    { name: "PSN 6", position: 146.0, region: "Indonesia, Pacific" },
    { name: "Telstar 11N", position: -37.5, region: "Americas, Europe, Africa" },
    { name: "Telstar 12V", position: -15.0, region: "Americas, Europe, Africa" },
    { name: "Telstar 18V", position: 138.0, region: "Asia Pacific" },
    { name: "Telstar 19V", position: -63.0, region: "Americas" },
    { name: "NSS-12", position: 57.0, region: "Europe, Middle East, Africa" },
    { name: "NSS-7", position: -22.0, region: "Atlantic, Americas" },
    { name: "NSS-9", position: 183.0, region: "Pacific" },
    { name: "Hylas 1", position: 33.5, region: "Europe" },
    { name: "Hylas 2", position: 31.0, region: "Europe, Middle East, Africa" },
    { name: "Hylas 4", position: 33.5, region: "Europe, Africa" },
    { name: "Yahsat 1A", position: 52.5, region: "Middle East, Africa" },
    { name: "Yahsat 1B", position: 47.5, region: "Middle East, Africa, Asia" },
    { name: "Al Yah 3", position: -20.0, region: "Americas, Africa" },
    { name: "Bangabandhu-1", position: 119.1, region: "Bangladesh, South Asia" },
    { name: "Kacific 1", position: 150.0, region: "Asia Pacific" },
];

// Sort satellites by orbital position
SATELLITES.sort((a, b) => a.position - b.position);

// Export for use in other modules
window.SATELLITES = SATELLITES;
